# Generated by Django 4.2.3 on 2023-10-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SF', 'Sofa'), ('LM', 'Lamp'), ('KT', 'Kitchen_Decor'), ('KD', 'Kid_Decor'), ('IP', 'Indoor_Plant')], max_length=2),
        ),
    ]
